### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by isfaaghyth** [mAlwiMhfd/tugasWeb#1]
wi, tadi masalahnya apa di [form_prodi](https://github.com/mAlwiMhfd/tugasWeb/blob/master/form_prodi.php) ?

**Comment by mAlwiMhfd** [comment]
Pas di validate nya gk bisa, padahal udah di require harus di isi, tapi
bisa muncul pesan require nya cuma kalo d refresh, kalo gk d refresh dulu
gk mau jalan

**Comment by isfaaghyth** [comment]
ok, ntar ku coba ya wi. 😄

**Comment by mAlwiMhfd** [comment]
Ok, maaf nih jadi ngerepotin

**Comment by mAlwiMhfd** [comment]
Bang sudah Alhamdulillah sudah selesai masalahnya
